### ISSUE TITLE
Update to use the new uPortal 5 config scheme

### ISSUE THREAD

**Issue by jhelmer-unicon** [uPortal-Project/soffit-samples#2]
You can override the value of most configuration settings using one or both of the following local configuration files:

- soffit-samples.properties
- global.properties

Both files are optional. notification.properties is for soffit-sample-only settings, whereas global.properties 
is for settings that may also be read and used by uPortal Modules (such as portlets). Both files support all the same settings. If the same setting is defined in both files, the value in soffit-sample.properties "wins." Both files (if you're using them) must be placed in the portal.home directory. The default location of portal.home is '$
{catalina.base}
/portal', but you can specify your own location by defining a PORTAL_HOME environment variable.

**Comment by jhelmer-unicon** [comment]
https://github.com/uPortal-Project/soffit-samples/pull/3

**Comment by drewwills** [comment]
merged
